### ISSUE TITLE
Incorrect refdes in documentation

### ISSUE THREAD

**Issue by hydra** [vespaman/Smoothieware-CHMT#1]
![image](https://github.com/vespaman/Smoothieware-CHMT/assets/57075/0b52e1ff-5675-4cec-bdd2-32ac284cf055)

Documentation refers to U31, when it should be referring to U28.  U31 is for the unpopulated 4 pin component towards the edge of the board.

**Comment by hydra** [comment]
Same goes for references to U33 which should be changed to U32.

**Comment by vespaman** [comment]
Thank's, for finding and reporting! I have updated accordingly.
