### ISSUE TITLE
Incorrect component name

### ISSUE THREAD

**Issue by hydra** [vespaman/Smoothieware-CHMT#2]
Documentation mentions `ADUM121NOBRZ-RL7`, but the `O` is actually a `0`, i.e: `ADUM121N0BRZ-RL7`.

https://www.lcsc.com/product-detail/Digital-Isolators_Analog-Devices-ADUM121N0BRZ-RL7_C660274.html

**Comment by vespaman** [comment]
Updated, thanks!
